language: cpp

sudo: required

matrix:
  include:
    - os: linux
      env:
        - system="i686"
    - os: linux
      env:
        - system="x86_64"
    - os: osx
      osx_image: xcode8
      env:
        - system="i686"
    - os: osx
      osx_image: xcode8
      env:
        - system="x86_64"

before_install:
  - source .travis/setenv.sh

script: make

branches:
  only:
    - master

notifications:
  email: false
