language: cpp

sudo: required

matrix:
  include:
    - os: linux
      env:
        - system="i686-linux"
    - os: linux
      env:
        - system="x86_64-linux"
    - os: osx
      osx_image: xcode8
      env:
        - system="x86_64-darwin"

before_install:
  - source .travis/setenv.sh

script:
  - make

branches:
  except:
    - chromium-gn

notifications:
  email: false
